// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASM-ydxU8VP5kDvEwLaDreHIM6xTb-AYE',
    appId: '1:651290502469:web:07f83978e6c0f04e5a0a2c',
    messagingSenderId: '651290502469',
    projectId: 'career-5d13c',
    authDomain: 'career-5d13c.firebaseapp.com',
    databaseURL: 'https://career-5d13c-default-rtdb.firebaseio.com',
    storageBucket: 'career-5d13c.firebasestorage.app',
    measurementId: 'G-EJ5HZFKYQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CepFEmjQ2J7ydOVK-qSKgeQB_1QSKuo',
    appId: '1:651290502469:android:e2132ecc08b22f2d5a0a2c',
    messagingSenderId: '651290502469',
    projectId: 'career-5d13c',
    databaseURL: 'https://career-5d13c-default-rtdb.firebaseio.com',
    storageBucket: 'career-5d13c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALSbqygSJ05mmYPl8IEE8mSqnj0reWwKU',
    appId: '1:651290502469:ios:ce200b92a55bfab45a0a2c',
    messagingSenderId: '651290502469',
    projectId: 'career-5d13c',
    databaseURL: 'https://career-5d13c-default-rtdb.firebaseio.com',
    storageBucket: 'career-5d13c.firebasestorage.app',
    iosBundleId: 'com.example.career',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALSbqygSJ05mmYPl8IEE8mSqnj0reWwKU',
    appId: '1:651290502469:ios:ce200b92a55bfab45a0a2c',
    messagingSenderId: '651290502469',
    projectId: 'career-5d13c',
    databaseURL: 'https://career-5d13c-default-rtdb.firebaseio.com',
    storageBucket: 'career-5d13c.firebasestorage.app',
    iosBundleId: 'com.example.career',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASM-ydxU8VP5kDvEwLaDreHIM6xTb-AYE',
    appId: '1:651290502469:web:94acc7bde3a9db7c5a0a2c',
    messagingSenderId: '651290502469',
    projectId: 'career-5d13c',
    authDomain: 'career-5d13c.firebaseapp.com',
    databaseURL: 'https://career-5d13c-default-rtdb.firebaseio.com',
    storageBucket: 'career-5d13c.firebasestorage.app',
    measurementId: 'G-3NR3BYSX3E',
  );
}
